### ISSUE TITLE
sandbox escape

### ISSUE THREAD

**Issue by eti1** [Rapporter/sandboxR#2]
Both are working:

e<-as.environment('package:base'); 
s<-e$get("system",envir=e)
s("echo hello",intern=TRUE)

e<-.BaseNamespaceEnv
s<-e$get("system",envir=e)
s("echo hello",intern=TRUE)

**Comment by daroczig** [comment]
Thank you very much for reporting these issues, I have just updated the playground: https://github.com/Rapporter/sandboxR/compare/b8b4c566f4a7aaccb529e13a7f77b9d8209ebbc4...master
