### ISSUE TITLE
ERROR: dependency 'parser' is not available for package 'sandboxR'

### ISSUE THREAD

**Issue by PeterVermont** [Rapporter/sandboxR#5]
Tried installing devtools::install_github("lq/parser") but that also failed:

gram.o:gram.c:(.text+0x1f7c): undefined reference to `Ri18n_wctype'
gram.o:gram.c:(.text+0x1f90): undefined reference to `Ri18n_iswctype'
gram.o:gram.c:(.text+0x24c1): undefined reference to `libintl_ngettext'
gram.o:gram.c:(.text+0x3020): undefined reference to `Rf_ucstomb'

**Comment by daroczig** [comment]
The `parser` package is no longer required since R 3.0.0 as it was integrated into base R. Can you please check the `r-3.0.0` branch and report back if that works?

**Comment by PeterVermont** [comment]
Thank you for your quick reply. Two things:
Why don't you change your default branch to r-3.0.0?
And two: would like an option for pretest and sandbox to not automatically stop -- if I get a false result I would prefer to put my own message that gives more context.

In any case, thanks for this -- it makes me feel more comfortable not to run arbitrary code even if my audience is internal to my organization.

**Comment by daroczig** [comment]
Sorry, I missed your above reply.

> Why don't you change your default branch to r-3.0.0?

This repo is not really maintained anymore, and although it works fine with most recent R versions, I'd like to leave this as is showing to visitors that it's under active dev.

> would like an option for pretest and sandbox to not automatically stop

Yeah, although unlikely to happen in the near future, as I'm focusing on some other projects. Would be happy to review a PR, though. On the other hand, you can achieve that with the current codebase by wrapping the sandboxR calls in `tryCatch` and providing your custom error message on error
